qfieldsync/core/layer.py, qfieldsync/core/offline_converter.py
this keep existent data on the disk
=> [fix #46] add option copy if missing

qfieldsync/core/project.py, qfieldsync/dialogs/synchronize_dialog.py, qfieldsync/utils/file_utils.py, qfieldsync/utils/qgis_utils.py
Checksum of last imported data.gpkg file (md5 hash) is stored in the project.
If trying to synchronize data from the same file (same checksum) again, it won't work.
=> Only synchronize data-file once

qfieldsync/qfield_sync.py
=> Assume default locale when locale is unset

qfieldsync/core/layer.py, qfieldsync/dialogs/project_configuration_dialog.py
=> Fix unsupported layer warning

qfieldsync/dialogs/synchronize_dialog.py, qfieldsync/utils/file_utils.py
=> Only calculate md5sum if offline editing done

.gitignore, qfieldsync/core/layer.py, qfieldsync/gui/__init__.py, qfieldsync/gui/project_configuration_dialog.py, qfieldsync/gui/resources_rc.py, qfieldsync/ui/project_configuration_dialog.ui, qfieldsync/utils/exceptions.py, qfieldsync/utils/file_utils.py
=> add table to define photo naming

qfieldsync/core/layer.py
Fixes https://github.com/opengisch/qfieldsync/issues/149
https://stackoverflow.com/a/18351977/2319028
=> Fix exception on warning

qfieldsync/core/offline_converter.py
Especially on translated installations, where the offline layer name could be translated (`name (hors ligne)` or similar)
References #155
=> Make value relation offline editing more stable

qfieldsync/core/layer.py
=> Sanitize default picture name format

qfieldsync/core/layer.py
This is a pretty bad regression _I introduced_ when doing localized path work on qfieldsync. Long story short, exporting projects to a qfield "package" would remove any substring filter attached to layers. 
IMHO, this requires a new qfieldsync release ASAP.
=> Fix subset string loss when exporting/packaging project

.docker/docker-compose.gh.yml, .github/workflows/continuous_integration.yml
Migrate the `.travis.yml` to GitHub Workflows. Probably will fail due to missing secrets now
=> Release using GitHub Workflows

qfieldsync/core/offline_converter.py
=> fix the value relation reference loose layer id matching

qfieldsync/core/offline_converter.py, qfieldsync/gui/package_dialog.py
in my case, the field was not shown in the form.
a complementary fix would be to parse only shown fields
=> add warning when a value relation has no layer set

qfieldsync/qfield_sync.py
Fix https://github.com/opengisch/qfieldsync/issues/232
=> Apparently OSX does not support & in the menu title

.github/workflows/continuous_integration.yml, qfieldsync/core/cloud_api.py, qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/metadata.txt, qfieldsync/tests/test_export.py, qfieldsync/ui/cloud_projects_dialog.ui, qfieldsync/ui/package_dialog.ui, qfieldsync/ui/project_configuration_widget.ui, qfieldsync/utils/permissions.py
=> WIP Additional cloud fixes

qfieldsync/gui/synchronize_dialog.py
Then it shows a confirmation box.
=> If originalProjectPath is not found, as to use the current project

qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_converter_dialog.py, qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/qfield_sync.py
Fixes #272
This was introduced from Mathieu's changes and is present only in the latest version.
=> Fix showing login dialog twice after logout

qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui, qfieldsync/utils/qgis_utils.py
=> Warn if the layer contains memory layers

qfieldsync/gui/synchronize_dialog.py, qfieldsync/utils/qgis_utils.py
Fixes #225 . It was discarding ANY unsaved changes, which was can be considered quite bad.
=> Create backup on sync back, otherwise we lose the unsaved changes

qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_converter_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui
How did we download before:
1) get all the redirect links
2) start downloading
How do we download now:
1) get a redirect link, redirect and start downloading
fix #268
There is also advanced log:
=> Fix ultra big downloads

qfieldsync/gui/cloud_transfer_dialog.py
=> Prefix local project dir with the owner's username, when it's not the logged user

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/qfield_sync.py, qfieldsync/resources/cloud_convert_project.svg
=> Add separators to the toolbar

qfieldsync/core/cloud_project.py, qfieldsync/core/cloud_transferrer.py
Seems to work with:
```
DCIM/filename1.jpg
DCIM///filename1.jpg
DCIM\filename2.jpg
DCIM\\filename3.jpg
```
closes #282
=> Fix downloading weird project filenames with forward/backward slashes

qfieldsync/core/cloud_api.py, qfieldsync/core/preferences.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/qfield_sync.py, qfieldsync/ui/cloud_transfer_dialog.ui
Minor, but timeconsuming...
Check the commit messages to see what have changed.
=> QFieldCloud integration minor fixes

qfieldsync/core/cloud_api.py, qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui, qfieldsync/utils/qt_utils.py
- UI added avatar on the right
- API moved the whole login login into `CloudApi`
=> Added avatar support

.github/workflows/continuous_integration.yml
Compatibility with Python 3.7 /osgeo installer v1
=> Fix typing yet again

qfieldsync/core/cloud_api.py, qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py
- Improve initial login experience (fix #311)
- Fix disabled QGIS toolbar and menu on escape of the login dialog (fix #311)
- Enabled updating project settings (fix #312)
- Fix local dir path out of sync when a dir needs to be created
- Fix removed underscores when creating a project ( fix #314)
- Bump libqfieldsync to support Python prior to 3.8 (fix #310)
=> Login and project update improvements and fixes

qfieldsync/core/cloud_converter.py
Fixes https://github.com/opengisch/qfieldsync/issues/315
=> Avoid deleting layers beore last usage

qfieldsync/qfield_sync.py
| before | after |
|----------|--------|
| ![image](https://user-images.githubusercontent.com/2820439/135266065-adafead4-8db3-4c71-9046-344de5843af9.png) | ![image](https://user-images.githubusercontent.com/2820439/135265762-20757412-41a4-4809-b182-557e0382ee32.png) |
=> Fix icons on Windows in 3.16

qfieldsync/gui/package_dialog.py, qfieldsync/metadata.txt
=> Tell the user that the packaging failed and show the python error

qfieldsync/ui/cloud_transfer_dialog.ui
=> Rename the last column header in the cloud synchronization dialog to Action

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui
=> Open the current project directory button

qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py
Hard to reproduce, but debugger pointed to here and now I am sure it is fixed.
=> Fix a python error when transfering files

qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_transfer_dialog.py
=> Don't show successfully synced message if there were some error during sync

qfieldsync/core/cloud_api.py, qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py
- simplifies and encapsulates logic
- supports download with and without redirect
=> Move the upload/download/delete http calls in the FileTransfer class

qfieldsync/utils/cloud_utils.py
=> Fix inverted logic and weird feedback when a project is cloudified

qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui
Should be better now, even though not perfect.
=> Improve the instructions on the synchronize dialog

qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_projects_dialog.py
=> Show feedback whether the uploaded project file is usable by QFieldCloud

qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_projects_dialog.py
=> Show feedback when a file is locally deleted

qfieldsync/core/cloud_api.py
Fix https://github.com/opengisch/qfieldcloud/issues/68
=> Disable the default timeout of 60 secs that QGIS has

qfieldsync/core/cloud_api.py
@nirvn should fix your issue with self-signed or unknown authority certificate.
=> Always use the singleton QgsNetworkAccessManager instance, otherwise ssl handling is impossible from python

qfieldsync/core/cloud_api.py
=> Worst typo in history breaks downloading

qfieldsync/gui/cloud_create_project_widget.py
@nirvn can you confirm it works fine? I tested with two (small) projects and seems to be much better UX.
=> Don't block the main thread when cloudifying a project so the UI updates

qfieldsync/gui/package_dialog.py
=> Fix QFieldSync package dialog if no project is open

qfieldsync/ui/cloud_transfer_dialog.ui, qfieldsync/ui/package_dialog.ui
Also make the project checker feedback full height
=> Bump libqfieldsync, less annoyance

qfieldsync/ui/cloud_transfer_dialog.ui, qfieldsync/ui/package_dialog.ui
=> Add explanations to the new project checker

qfieldsync/core/cloud_project.py
=> Avoid hidden files and directories (POSIX only)

qfieldsync/gui/cloud_browser_tree.py
I love asserts, pointed me directly to the issue <3
=> Fix creating a new project from the browser panel

README.md, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/metadata.txt
Also removed the gitter link, as it is far from active.
=> Fixed the links to point to the new docs

qfieldsync/core/cloud_api.py
Fix https://github.com/opengisch/QField/issues/2537 
Fix https://github.com/opengisch/qfieldsync/issues/391
=> Fix QGIS 3.16 because setTimeout(0) make requests fail immediately

qfieldsync/core/cloud_transferrer.py
Also the early return was causing the UI to stay in an undefined state.
=> If the request is not successful, do not download the response contents

qfieldsync/core/cloud_api.py, qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_login_dialog.ui, qfieldsync/ui/preferences_widget.ui
=> Rename log in to sign in; Add reset password and register an account links

.pre-commit-config.yaml, qfieldsync/core/cloud_api.py, qfieldsync/gui/cloud_browser_tree.py
=> Bump pre-commit black version

qfieldsync/core/cloud_transferrer.py, qfieldsync/ui/project_configuration_widget.ui
Fixing a few orthographic errors spotted during translation.
=> Orthographic fix on text strings

qfieldsync/gui/layers_config_widget.py
While https://github.com/opengisch/qfieldsync/issues/413 is unpleasent, it is not as bad as the errors reported on #425 and #426 . Will revisit my solution and try to fix it again after 4.1.1 is released.
=> Reverted changes fixing #413 , but causing problems saving project settings

qfieldsync/gui/package_dialog.py
This PR fixes https://github.com/opengisch/QField/issues/3047 .
=> Fix successful cable export message bar hyperlink on windows

qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_projects_dialog.py
=> Show nicer error when the project name already existing for given owner

qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_projects_dialog.py
=> Reselect the project after projects refresh or creating a new one

qfieldsync/core/message_bus.py, qfieldsync/gui/layers_config_widget.py, qfieldsync/gui/map_layer_config_widget.py
Fix https://github.com/opengisch/qfieldsync/issues/413 again.
Follow up of https://github.com/opengisch/qfieldsync/pull/428/files
=> Added a poor man message bus to inform the project settings that sth changed in layer settings

qfieldsync/gui/cloud_create_project_widget.py
=> Fix setting the description on project creation (#460)

qfieldsync/core/cloud_api.py
Fix the `include-public` param value from `true` to `1`.
=> Do not attempt downloading public projects by default

qfieldsync/gui/package_dialog.py, qfieldsync/ui/package_dialog.ui
=> Don't immediately close the package project dialog on save

.github/workflows/continuous_integration.yml, .pre-commit-config.yaml, qfieldsync/core/preferences.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/ui/synchronize_dialog.ui, qfieldsync/utils/file_utils.py, qfieldsync/utils/qt_utils.py
Sample project:
[qfs_478_dirs_to_copy.zip](https://github.com/opengisch/qfieldsync/files/10020875/qfs_478_dirs_to_copy.zip)
=> Select subdirs in exported project to be copied back to the main project

.pre-commit-config.yaml, qfieldsync/gui/attachment_naming_widget.py, qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/resource_naming_widget.py
See https://github.com/opengisch/QField/pull/3851 on the QField side and the recent work done in QGIS itself such as https://github.com/qgis/QGIS/pull/51594.
Relevant libqfieldsync PR: https://github.com/opengisch/libqfieldsync/pull/41
UI slightly changed to add a tips label:
=> Move away from photo-centric external resource support into file,image,audio,video

qfieldsync/core/preferences.py, qfieldsync/gui/dirs_to_copy_widget.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/ui/dirs_to_copy_widget.ui, qfieldsync/ui/package_dialog.ui, qfieldsync/ui/synchronize_dialog.ui
=> Added the dirs to copy functionality to the package dialog

qfieldsync/gui/cloud_login_dialog.py
=> Show wait cursor during login

qfieldsync/__init__.py, qfieldsync/gui/attachment_naming_widget.py, qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/gui/dirs_to_copy_widget.py, qfieldsync/gui/layers_config_widget.py, qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/preferences_widget.py, qfieldsync/gui/relationship_configuration_widget.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/gui/utils.py
As suggested in https://github.com/opengisch/qfieldsync/pull/519#discussion_r1218903023
=> QField does more than Android !

qfieldsync/metadata.txt
@m-kuhn @mbernasocchi feel free to add more.
=> Add some more plugin metadata tags

qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/ui/cloud_create_project_widget.ui
| before | after |
|-|-|
| ![image](https://github.com/opengisch/qfieldsync/assets/2820439/106c84ec-e9aa-4e19-a7b9-ffe215d7e30b) | ![image](https://github.com/opengisch/qfieldsync/assets/2820439/5e615ff7-331d-48b8-85e6-b9d7ee3e7752) |
=> Make it possible to select project owner during project creation

.github/workflows/continuous_integration.yml, qfieldsync/gui/checker_feedback_table.py, qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/gui/package_dialog.py, qfieldsync/tests/test_export.py, qfieldsync/ui/cloud_transfer_dialog.ui, qfieldsync/ui/package_dialog.ui
| before | after | 
|-|-|
| ![image](https://github.com/opengisch/qfieldsync/assets/2820439/2bd4e801-0746-4204-8d55-14e02ea5a7b3) | ![image](https://github.com/opengisch/qfieldsync/assets/2820439/1f1d56f4-858c-4b3e-814b-7bfc3f42ad05) |
=> Improved checker feedback screen

qfieldsync/qfield_sync.py
=> Add Plugins menu icon for QFieldSync

qfieldsync/ui/cloud_login_dialog.ui
- Remember me checkbox
- Error messages
- New user registration
Before
After
=> Give full with to login dialog widgets

qfieldsync/core/preferences.py, qfieldsync/qfield_sync.py
@suricactus , @m-kuhn , as discussed.
=> Set default packaging toolbar visibility preference to true & add first run check

qfieldsync/gui/cloud_transfer_dialog.py
Should fix https://github.com/opengisch/qfieldsync/issues/517
=> Prevent rendering the files to be transfered twice

qfieldsync/gui/map_layer_config_widget.py, qfieldsync/ui/map_layer_config_widget.ui, requirements.txt
I'll let the screenshot do the talking :)
(requires libqfieldsync' s https://github.com/opengisch/libqfieldsync/pull/71)
=> Tracking session UI

qfieldsync/gui/package_dialog.py
If libqfieldsync requires a reload.
Fixes https://github.com/opengisch/qfieldsync/issues/575
=> Add warning to restart QGIS

qfieldsync/gui/dirs_to_copy_widget.py
This pull request fixes the issue reposted in issue [#499](https://github.com/opengisch/qfieldsync/issues/499)
https://github.com/user-attachments/assets/eeed40c8-e456-4957-98ba-09ce919c10ca
=> First attempt to fix the select/deselect all folder in QFieldSync

qfieldsync/gui/checker_feedback_table.py
Fix https://github.com/opengisch/qfieldsync/issues/596
=> Make sure the dialog buttons are still clickable with long feedback

requirements.txt
Fix opengisch/qfieldsync#604
See https://github.com/opengisch/libqfieldsync/pull/92
=> Fix project cloud convert code

qfieldsync/gui/layers_config_widget.py, qfieldsync/ui/layers_config_widget.ui
This PR integrates enhancements to the functionality mentioned in issue [#438](https://github.com/opengisch/qfieldsync/issues/438)
https://github.com/user-attachments/assets/70072970-a7e6-4f8e-93ec-c0e9f5117a9f
=> Filters visible layers for packaging offline project

qfieldsync/ui/cloud_transfer_dialog.ui
=> Fix invalid stylesheet for projectLocalDirValueLineEdit

qfieldsync/core/cloud_api.py, qfieldsync/core/cloud_project.py
Drastically speed up projects with a lot of files in them.
=> Use the etag to check whether the file should be synced or not

qfieldsync/core/cloud_api.py
Fixing https://github.com/opengisch/qfieldsync/issues/510
=> Fixing misleading error message by no network available

requirements.txt
To include https://github.com/opengisch/libqfieldsync/pull/99
Fixes #630
=> Bump libqfieldsync

requirements.txt
Fix https://github.com/opengisch/qfieldsync/issues/633#event-16132615384
=> Bump libqfieldsync to fix backward incompatible changes by GDAL 3.10.0+

requirements.txt
- Add support for embedding symbols https://github.com/opengisch/libqfieldsync/pull/107
- ...probably something else I might have missed
=> Bump libqfieldsync to the latest

qfieldsync/ui/cloud_login_dialog.ui
=> Fixing the tooltip to the QFieldCloudIcon

qfieldsync/core/cloud_api.py, qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_transfer_dialog.py, requirements.txt
Removed this warning:
And added this tooltip:
=> Add tooltip about missing localized files that need to be uploaded

qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/package_dialog.py, qfieldsync/ui/cloud_create_project_widget.ui, qfieldsync/ui/cloud_projects_dialog.ui, qfieldsync/ui/package_dialog.ui
Attempt to fix #670 .
I am not super happy with the end result, if @nirvn has a better understanding how QSrollArea works, feel free to hijack the branch.
=> Add a scrollbar when there are too many localized datasets

qfieldsync/ui/image_stamping_configuration_widget.ui
Fixes https://github.com/opengisch/qfieldsync/issues/696 https://github.com/opengisch/qfieldsync/issues/699
=> Fix font button error when activating qfieldsync

qfieldsync/gui/layers_config_widget.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/layers_config_widget.ui, qfieldsync/ui/project_configuration_widget.ui
This is how it looks:
| Before | After |
| --- | --- |
| ![](https://github.com/user-attachments/assets/1de5ff7a-7d43-42a5-809d-fd83da6306bc) | ![](https://github.com/user-attachments/assets/bc55d17e-d06c-42a5-ad90-bcd51d80fa50) |
=> Changing the Radio buttons to QToolButton

qfieldsync/gui/map_layer_config_widget.py, qfieldsync/ui/map_layer_config_widget.ui, requirements.txt
Adds a checkbox in the layer configuration to allow adding new features to value relation editor widgets.
=> Adds option to allow feature addition in value relation

qfieldsync/gui/package_dialog.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/tests/test_export.py, requirements.txt
See https://github.com/opengisch/libqfieldsync/pull/123
=> Adjustments to the stricter linter in libqfieldsync

qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_transfer_dialog.py
=> fix: use the newly provided `uploaded_at` field and fix the expected date format of the fallback `last_modified` field
