opengisch/qfieldsync

.travis.yml, qfieldsync/__init__.py, qfieldsync/core/layer.py, qfieldsync/core/offline_converter.py, qfieldsync/dialogs/package_dialog.py, qfieldsync/dialogs/project_configuration_dialog.py, qfieldsync/processing/basemap.py, qfieldsync/tests/__init__.py, scripts/ci/install_qgis2compat.sh, tox.ini
It was causing too much troubles and with the current state of API breaks is no longer considered a feasible migration path.
=> Drop qgis2compat dependency

qfieldsync/core/offline_converter.py
The offline_editing function is called defaultly with the containertype 1 for Geopackage - on error make sqlite like before. 
I was not yet able to test this implementation.
=> GPKG per default

qfieldsync/core/offline_converter.py, qfieldsync/core/project.py, qfieldsync/dialogs/synchronize_dialog.py, qfieldsync/utils/qgis_utils.py
On the very last moment on creating an offline project, the absolute path of the original project is written to the offline-project. On synchronization after done, this project is tried to be opened again.
=> Open original project after synchronization

qfieldsync/core/layer.py, qfieldsync/core/offline_converter.py
So the GPKG file is copied if a layer has this option.
In case there are several layer in this file, they are all copied. But only the ones with "copy" option are used from there. In case a GPKG layer has the option "offline editing" it has as the source the usual "data.gpkg" and if the GPKG layer has the option "remove" it's not in the project at all.
This fixes https://github.com/opengisch/Vogelwarte_QField_2019/issues/7
=> "copy" option (instead of "no action") for GPKG layer

qfieldsync/core/offline_converter.py
Disable EvaluateDefaultValues and AutoTransaction options on exported projects to avoid possible synchronization problems with geopackages.
=> Disable EvaluateDefaultValues and AutoTransaction options

qfieldsync/gui/project_configuration_dialog.py
- Check if layer is vector layer on attachment fields
- use row as index
Before I received this:
```
2020-03-02T14:48:25     WARNING    Traceback (most recent call last):
File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py", line 94, in 
self.infoLabel.linkActivated.connect(lambda: self.show_settings())
File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py", line 153, in show_settings
dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/project_configuration_dialog.py", line 79, in __init__
self.reloadProject()
File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plu …
```
=> Photo_path fixes

qfieldsync/core/layer.py, qfieldsync/gui/project_configuration_dialog.py
The user should configure the extension and can be able to set other extensions than jpg.
See what QField does:
https://github.com/opengisch/QField/pull/790#issue-368538835
=> Extensions `||.jpg` in default photo_path expression

qfieldsync/gui/project_configuration_dialog.py, qfieldsync/utils/file_utils.py
- Correct slugify of layername on default values to have the uppercase letters lowercase
- initialize the layer source only once per layer: fixes that it could not store all edits (it only stored the last edit of a layer_source)
- make the display of this feature depended on the QGIS version
=> Fixes on photo path configuration

qfieldsync/gui/package_dialog.py
fixes #124 follow up
following discussion in #124, when the project has already been exported, the exported directory is kept as a project setting and reused. 
There was a leftover, which was re-adding the project name as a subfolder (which is used on first time for a project, when no folder has been saved already).
=> do not re-add project folder if it already is defined

qfieldsync/core/offline_converter.py
When the value-list-layer of a value relation widget is made offline, the widget still "points" to the online layer.
This pull request fixes this issue and updates the layer accordingly.
=> Fix value relations with offline editing

qfieldsync/core/layer.py, qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/photo_naming_widget.py, qfieldsync/gui/project_configuration_dialog.py, qfieldsync/gui/utils.py, qfieldsync/qfield_sync.py, qfieldsync/ui/map_layer_config_widget.ui, qfieldsync/ui/project_configuration_dialog.ui
Add a new layer option to "lock geometries". This new option should ideally live on a new vector layer properties panel. QField should respect this new configuration option and not allow adding, splitting, modifying etc. geometries.
https://github.com/opengisch/QField/pull/1063 functionality:
=> FEATURE add option to lock geometries

qfieldsync/core/offline_converter.py
pylupdate5 hardcodes the output to ascii symbols, therefore any unicode is XML encoded and cannot be reverted to the original state.
Enforcing `codecForTr` to be utf8 does not work:
https://github.com/baoboa/pyqt5/blob/31ef42563dbcaf3885da8803e2e5d84507141c9b/pylupdate/pylupdate_main.py#L231
As the output is hardcoded as ASCII in
https://github.com/baoboa/pyqt5/blob/31ef42563dbcaf3885da8803e2e5d84507141c9b/pylupdate/metatranslator.cpp#L435
=> Use three dots instead of elipsis

qfieldsync/core/layer.py, qfieldsync/core/offline_converter.py
COPY action instead of NO_ACTION when it's a file based source.
This because QField is taking this information since using it with the cloud.
And it has to make a difference if it's an online DB connected directly or if it's a file based layer updated via QFieldCloud.
=> copy action

qfieldsync/metadata.txt
@m-kuhn , as suggested a while back, I think we can lower burden pushing a new qfieldsync plugin release by having a generic changelog metadata (vs. one that's not up-to-date :) ).
=> Update metadata changelog with generic message instead of obsolete information

qfieldsync/utils/file_utils.py
Fix error stack thrown when trying to import/synchronize data from a non-existing directory
=> Fix error stack thrown when trying to import/synchronize data from a non-existing directory

qfieldsync/core/layer.py, qfieldsync/core/offline_converter.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui
Improvements around unsupported layers handling:
- QField has been supporting JP2K rasters for a while now, thanks to @m-kuhn , let's not report those as unsupported
- Never package unsupported datasets (as of now only one format: ECW), it's a waste of bandwidth and let's to errors in QField
- Don't show an "invalid/unsupported layers" label if none are detected
Fixes #78
=> Further project properties improvements

qfieldsync/core/offline_converter.py, qfieldsync/core/project.py
Allow users to work with current feature selection when converting to offline project.
This PR enables more complex scenarios like splitting a whole dataset into subsets per surveyor.
Note: Only API (GUI in https://github.com/SwissTierrasColombia/qfieldsync/commit/c1893e211aab2a9c877d75f1413f9d8da933ab10)
=> Only copy selected features for offline layers

qfieldsync/core/offline_converter.py, qfieldsync/tests/data/pk_project/project.qgs, qfieldsync/tests/test_export.py
Store the primary key field name(s) of offline layers as layer custom property.
The value is stored as a comma-separated list into the `QFieldSync/cloudPrimaryKeys` layer's property
=> Store primary key field names as layer custom property

qfieldsync/gui/layers_config_widget.py, qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/photo_naming_widget.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/gui/utils.py, qfieldsync/ui/layers_config_widget.ui, qfieldsync/ui/map_layer_config_widget.ui, qfieldsync/ui/project_configuration_widget.ui
More or less the UI I managed to produce is this. Any feedback is welcome, I am not completely happy how it looks. Notable changes:
- now there is `LayerSource.action` and `LayerSource.cloud_action`
- the image naming is moved only in the per layer settings (no more in project settings)
- the "Basemap" configuration is moved out of the tab and it is a checkable box whether to be enabled or not
A note on the "Prefer Off/Online Layers" - it will ignore toggling the layer action, if the layer is already marked as "Remove from Project", it will be annoying if it restarts the action every time.
The last remaining issue is with lock geometry, I need ideas where to move it. It is not kept in sync between the "Cloud" and "Cable" tabs, only the latter is taken. I believe we can remove it from the …
=> Split the configuration for cloud and traditional cable export

qfieldsync/core/offline_converter.py, qfieldsync/tests/test_export.py
Since this https://github.com/qgis/QGIS/pull/39492 the suffix ` (offline)` can be avoided to avoid issues with expressions etc.
So let's don't use it anymore.
=> Don't use layer suffix ` (offline)`

qfieldsync/gui/project_configuration_widget.py
Using the *toggle layers* menu in the project properties would mess with the *Photo Naming* tab, adding a new table widget every time.
=> Stop adding new PhotoNamingTableWidgets on reloadProject

qfieldsync/core/offline_converter.py
Current implementation results in a destination filename:
*connection string_qfield.qgs*
in case of a postgres stored project.
=> Read baseName from project instance instead of filename

qfieldsync/gui/photo_naming_widget.py
=> Don't overexpand the photo naming table horizontally

qfieldsync/core/offline_converter.py
From QGIS 3.10 to QGIS 3.16, the qgis:rasterize processing tool changed it's parameters, specifically the "LAYER" parameter does not exist anymore, and has been replaced by the "LAYERS" parameter, expecting a list. This change fixes the QGIS 3.16 compatibility problem.
The symptom is that the raster created still exists, but instead of containing only one layer (normally the map layer) it contains by default all visible layers, therefore rasterizing not only the basemap but also the vectorial objects into it.
This change fixes the bug and makes the Qpackage compatible with QGIS 3.16 which is now the "long term stable" version.
=> qgis:rasterize processing tool changed it's parameters from QGIS 3.10 to QGIS 3.16

.github/workflows/continuous_integration.yml
Turns out QGIS no longer produces `final_3_XX_XX` docker tags, so I also switched to `release_3_10`.
=> Add QGIS 3.16 LTR in the test matrix

qfieldsync/gui/layers_config_widget.py, qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/map_layer_config_widget.ui, qfieldsync/ui/project_configuration_widget.ui
Screenshot:
- layer icons in the table widget to easily identify layer type (helps skip through the list)
- use proper spinners for numbers, add suffixes
- avoid double "advanced settings" group box, make the bottom advanced settings collapsible
- better placement / stretch / spacing of widgets all around
=> Improvements to project properties panel

qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui
A new digitizing logs layer combo box was added in the project properties' QField panel:
This is to accompany the new feature being developed for QField 2.0, see https://github.com/opengisch/QField/pull/1971
=> Add UI to pick a digitizing logs layer

qfieldsync/core/offline_converter.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/synchronize_dialog.py
Still not sure why the slots no longer work in 3.20, but they are not needed anyways.
Fixes https://github.com/opengisch/qfieldsync/issues/256
=> Kill pyqt slots for QGIS 3.20

qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/qfield_sync.py, qfieldsync/ui/cloud_transfer_dialog.ui
This is the last bit of UI/UX improvement I had on my to-do list for qfieldsync's QFieldCloud support.
This IMHO greatly improves the first-time download/synchronization of a cloud project that hasn't had a local directory set up yet. The changes include:
- Instead of being thrown a directory picker dialog out of nowhere, the synchronization dialog informs the user of what's happening
- To ease the process, a default local directory is provided (derived from the cloud project name and the default cloud directory set in the user preferences)
- Instead of being shown the intimidating file tree widget on first synchronization, proceed with downloading all files directly
- At the end of a successful download/synchronization, the user is provided with a useful checkbox to automatically load …
=> Improve synchornizing of cloud projects missing a local directory

qfieldsync/gui/cloud_browser_tree.py
This commit updates the browser panel cloud project item's double left click action for cloud projects that aren't locally present. Prior to now, a cloud project properties dialog would show up. IMHO, this isn't optimal. We should insure that a double left click action should always lead to a project being opened whether directly when a cloud project is locally available, or by relying on the revamped synchronization dialog that defaults to auto-opening downloaded/synchronized cloud projects.
The cloud project properties dialog remains accessible via right click on browser panel cloud items (matching behavior of other browser panel items, file explorers, etc.)
(Forgot this commit in my last PR)
=> Improve browser panel cloud project item's double click action

.github/workflows/stale.yml, qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_converter_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/ui/cloud_converter_dialog.ui, qfieldsync/ui/cloud_transfer_dialog.ui
- Convert visible filepaths with QDir.toNativeSeparators, so we dont get `C:\\users\suricactus/ugly/path`
- Fix implicit float -> int conversion warning
- Ensure unique empty dirname when selecting local project dir. It will try to create `~/qfield/cloud/project_name_1`, `~/qfield/cloud/project_name_2`, `~/qfield/cloud/project_name_55`, until it finds an nonexisting path or empty dir.
- Fix reset dirname - when deleting the dirname, it was impossible to force the empty value
- Prefer tool button - they look way better
=> Filepath selection and display improvements

qfieldsync/gui/cloud_converter_dialog.py, qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/qfield_sync.py, qfieldsync/ui/cloud_login_dialog.ui, qfieldsync/ui/preferences_widget.ui
After a quick discussion with @m-kuhn seems the "remember me" checkbox was exactly that, it was not doing the login. You will only be logged in on next session if you logged in and you have the possibility to log out. If someone intentionally never logs in, then all is good.
Enabled by default. 
Added a tooltip and changed it to "stay logged in":
Also fix #284
=> Add option to auto login

qfieldsync/core/cloud_api.py, qfieldsync/core/cloud_converter.py, qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_converter_dialog.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/utils/qgis_utils.py
UI/UX:
- suggest a unique project name
- suggest a unique local project directory
- add the opened project in "recent projects" history
- keep a backup of the original project
- append ` (QFieldCloud)` in the converted project
- set the title on the original project, if missing
Code:
- always prefer pathlib
- fix a few static analysis issues
- `folder` -> `directory`, sorry for the strong opinion on this :)
- python naming convention
=> Clodify converter improvements

qfieldsync/core/cloud_api.py
Hey there public/community cloud projects:
=> Fix missing public projects in the browser panel's qfieldcloud node

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/qfield_sync.py, qfieldsync/ui/cloud_projects_dialog.ui, qfieldsync/ui/cloud_transfer_dialog.ui
@suricactus , as discussed, this PR moves the memory layer warning to sit just above the standard buttons box.
The commit also hides the error label by default until there's an actual string in there. That removes the visually awkward spacing between the collapsing details box and the download progress bar.
Finally, the PR also improves the cloud projects dialog. Here's how it looks now:
- Add a convert current project to cloud project button
- Rework margins to save some white space and harmonize with other dialogs across QGIS
- Move the create blank project away from the projects list header into the newly introduced new cloud projects actions section and transform into into a push button so text appears on the button
@mbernasocchi , as suggested during the …
=> Tweaks to the cloud synchronization and projects dialogs

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui
Feeling inspired:
- massive de-cluttering of the table widget by moving the repeated actions tool button out of the table
- the set of actions now sit under the table widget (much like QGIS does in many other places) -> harmony
- relying on QGIS icons to both fit better in the overall QGIS desktop environment (bonus: we decrease icon maintenance burden on our side)
=> More love to the cloud projects dialog

qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui
GIF time:
- the cloud projects dialog now allow users to see and download / synchronize community projects (making the QGIS desktop experience closer to that of QField)
- relocating the refresh button to avoid awkward look following @suricactus 's fantastic avatar work
- renamed the browser panel QFieldCloud's "public projects" to "community" so we share the same keyword across QField, QGIS, and the web app
=> Add community projects to the cloud projects dialogs

qfieldsync/core/cloud_api.py
Because it's not great to see a red error bar every time you launch QGIS master with qfieldsync on ;)
=> Make qfieldsync less intimidating, fix red Qt error on QGIS boot

.gitignore, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui
- Disable "Is Private" checkbox in the project edit form. It is only editable using the web UI
- Keep the "Submit" button enabled even if the local project path is empty
- Do not update the local project path while editing, wait for "save" to be clicked
- Skip API update if there is nothing to be updated (name, descr). Allow updating project local path if you don't have permission to do so.
- Add .qt_for_python to .gitignore
=> Fixes while updating the project details

qfieldsync/core/cloud_project.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui
This PR improves the cloud synchronization process through two changes.
First, if users are synchronizing a project where they are assigned the role of 'reader', the UI will disable all upload-related functionality, simplifying the UI quite a lot:
The second is IMHO an important UX improvement: instead of always forcing uploads by default, the synchronization dialog will pick a better default based on last modified date. If the cloud-stored file has a modification date that's newer than the locally stored file, we now default to downloading from the cloud.
=> Cloud synchronization improvements

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/qfield_sync.py
The old solution cause the whole python environment in QGIS to change.
This will break so many scripts!  Fixes the fix in #327
=> Fix the icons without changing the current workdir globally

qfieldsync/gui/cloud_transfer_dialog.py
Title says it all. With this PR, the user will be aware of completely empty cloud project:
=> Do not pretend there is a project on completely empty cloud project

qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/qfield_sync.py
- Use CloudTransferDialog.show_transfer_dialog static method to prevent multiple dialogs
- If the updating the files list is unsuccessful before transferring, show an error message, instead of silently showing all the local files as changed.
=> UX when using the transferring dialog

qfieldsync/gui/cloud_create_project_widget.py
When creating a new empty project it wrongly shows a success message showing the files have been uploaded
=> Shows a success message only when files have been really uploaded

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui
We will need to open qfield (cloud) docs.
=> Add help button on the projects dialog that shows qfield.org/docs

qfieldsync/core/cloud_transferrer.py
Uploading a .qgs file triggers a job on the cloud and should be the last thing to upload, so there are no unexpected errors.
=> Upload the .qgs/.qgs file at the end of the file transfer

qfieldsync/gui/cloud_transfer_dialog.py
Until a better solution is found, better restore what was already working well enough.
=> Restore delete functionality

qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/cloud_transfer_dialog.ui, qfieldsync/ui/package_dialog.ui
Various checks were done all around the code: some withing QFieldSync, some withing libqfieldsync. Some were shown in advance, others during export.
With this PR I have added a unified code and user interface to perform those checks in advance and return a clear feedback what is ok and what needs to be changed.
If the `ProjectChecker` detects errors, it prevent the user from uploading to the cloud or packaging the project.
Some of the checks are also done withing libqfieldsync. After QFieldCloud gets aware of the new `ProjectChecker` API they can be removed.
Fix #238 
Fix #146 
Fix #299
=> QFieldSync should perform checks before uploading/packaging a project

qfieldsync/gui/cloud_projects_dialog.py, qfieldsync/ui/cloud_projects_dialog.ui
Tried my best to make it round, however applying custom CSS style is Qt kills all other styling.
=> Fix sign out if there is no avatar

qfieldsync/gui/cloud_projects_dialog.py
This PR fixes the logout button (now merged with the avatar display) going missing for avatar-less cloud accounts.
Our beautiful favorite bee acts as the avatar when missing:
=> Fix logout button missing for avatar-less accounts

qfieldsync/gui/cloud_create_project_widget.py
@suricactus , because of course dev accounts are already full of projects and we never hit this ;)
=> Remove assert in cloudify_project as new cloud users have _no_ projects, which have them hit the assert

qfieldsync/core/cloud_converter.py
The project cloudifier should be as friction-less as possible; set good default cloud actions to converted layers so when users hit the synchronize button, they aren't shown a scary dialog full of errors :)
Prevents this dialog from showing:
@jmad1v07 , this is something you were hitting while doing testing.
=> When cloudifying a project, auto set the approprite cloud action to avoid synchronization dialog errors

qfieldsync/core/cloud_converter.py
@suricactus , as suggested, the better way (tm).
=> Rely on default_cloud_action property when cloudifying

qfieldsync/gui/cloud_projects_dialog.py
The comment and the default value should be removed in the future.
=> QFieldSync should use the version display format from as provided from the API

qfieldsync/core/cloud_api.py
Otherwise we get:
```
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/cloud_api.py", line 392, in
lambda: self._on_cloud_get_download_finished(
File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/core/cloud_api.py", line 423, in _on_cloud_get_download_finished
if http_code >= 301 and http_code TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
=> Fix missing HTTP code from the reply for unknown reason

qfieldsync/gui/cloud_create_project_widget.py
We didn't escape if the project name is generated from the filename.
=> Make sure the suggested project name is valid when creating a new project on QFIeldCloud

.github/workflows/continuous_integration.yml
There is a problem releasing versions with `qgis-plugin-ci` and getting 400 errors from the RPC api endpoint. No idea why, but I would blame the leading `v` in front of the version.
So intead of `v4.0.0` I would try to release `4.0.0` from now on.
=> Try fixing the release workflow

qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui
Title says it all. The UI looks like this when no maximum is entered:
When a maximum is set:
The qfieldsync plugin side of https://github.com/opengisch/QField/pull/2740
=> Add a new project-level property to define maximum width/height of image attachments

qfieldsync/gui/layers_config_widget.py
When user opens layer properties via project properties and click Apply/Ok on both dialog windows, the layer settings (layer action or image path) get lost as they are cached in the layer source of the project properties window. This PR aims to fix this.
There are a few extra CPU cycles involved as the project "setdirty" signal is triggered multiple times.
Fix #413
=> Make sure the configuration made using project properties -> layer properties is not lost

.github/workflows/continuous_integration.yml
For whatever reason we did not see the args were duplicated.
Also, releasing with release version without the leading `v` was causing the plugin version not to be easily accessible on QGIS plugins repo.
=> Remove the release version parameter and cleanup duplicated args

qfieldsync/gui/layers_config_widget.py
Unfortunately there is no easy way to understand when the layer properties dialog was closed. On the other hand, depending on the `setDirty` event does not guarantee the wrapped C++ layer objects are not deleted.
Wrapping the code in try/except at least prevents the error popping up to the user until a better API is available.
=> Prevent python error popping up because of deleted QgsMapLayer

qfieldsync/core/cloud_converter.py, qfieldsync/core/preferences.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/tests/test_export.py, qfieldsync/ui/project_configuration_widget.ui
So far QFieldSync automatically syncs only the `DCIM` directory. Now this is the default behaviour, but the user can set a list of directories that can be copied in the package too.
=> Add "Attachement Directories" configuration on QFieldSync

.github/workflows/continuous_integration.yml, qfieldsync/core/cloud_api.py
Workaround to https://github.com/qgis/QGIS/issues/49687
=> Cut the response by the content length, so we can discard other bytes coming from buggy clients

qfieldsync/core/cloud_converter.py
This PR started with wanting to add safeguards to properly handle a subset of virtual (vector) layers, and ended up discovering a bad issue with the converter that must have led to quite a few failures out there.
First, virtual layer handling. When we detected such a layer, we check whether it is composed of only referenced layers (i.e. in the virtual layer SQL, we only refer to project layer names). If we have only referenced layers, we go ahead and keep the virtual layer in-place. If we detected non-referenced layers, we warn the user that it is not supported and remove it. It'll help users better understand the situation and take relevant actions.
As for the bad error, turns out setting custom properties to a layer that's been removed from the project (i.e. leading to a null pointer) …
=> Virtual layer handling + fix bad error that breaks cloud converter

.github/workflows/continuous_integration.yml, qfieldsync/core/cloud_api.py
Whenever QFC API is requested to list the project files, it asks the S3 API to return the list of files and versions. As the file list grows, it only gets slower. In their case it takes 1.5min+ to respond for 4k files.
1) Fastest: make the API respond with files only, so don't iterate 10*N files, but N only.
- server side changes, around 0.5-1 day
- qfieldsync changes, so it calls the new endpoint that serves the files.
2) Medium: store all file metadata in the DB, instead of polling the S3 storage. DB should be way faster.
- server side only, few days
3) Slow: we need to add pagination on pretty much all data.
- server side, few days
- qfieldsynnc
- qfield
- qfieldcloud-sdk
-
=> Increase the timeout for all requests to QFC

qfieldsync/gui/synchronize_dialog.py
This should fix https://github.com/opengisch/QField/issues/3896 -- not sure why 4.3.0 would have triggered the regression since none of the code / preference involved here is new. In any case, this commit harden the code.
=> Avoid crashing when the importDirectoryProject preference is not a valid JSON

qfieldsync/core/preferences.py, qfieldsync/gui/synchronize_dialog.py
By mistake it was set to a `Dictionary`, most probably when I was editing the next line `importDirsToCopy`.
This error caused regressions in 4.3.0 as reported in https://github.com/opengisch/QField/issues/3896
=> Revert `importDirectoryProject` to a preference of type `String`

qfieldsync/ui/project_configuration_widget.ui
Fix https://github.com/opengisch/qfieldsync/issues/475.  Can be quite annoying on smaller screens (and not only).
=> Make the QField tab in project preferences scrollable

qfieldsync/gui/attachment_naming_widget.py
In short, the `photo_naming` was renamed to `attachment_naming` and it broke
projects configured with older version as reported in #487 .
See https://github.com/opengisch/libqfieldsync/pull/42
=> Move most of the attachments logic within libqfieldsync

qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/ui/cloud_create_project_widget.ui
Also renamed the elements to have the same name to reduce cognitive needs.
| before | after |
|-|-|
| ![image](https://github.com/opengisch/qfieldsync/assets/2820439/2de34ae2-5fbe-490d-b5d2-b109404b0e69) | ![image](https://github.com/opengisch/qfieldsync/assets/2820439/c137f52e-58a8-445d-8be5-e5149d788225) |
=> Make project form on create and edit to look more similar

qfieldsync/core/cloud_api.py
EDIT:
Even better now.
---
So far it was showing "Failed to login: None"
Fixes #511
=> Show server side error when login failed

qfieldsync/gui/cloud_login_dialog.py, qfieldsync/gui/cloud_projects_dialog.py
Calling raise() and activateWindow() is used to insure dialogs are raised to the top, let's call this to avoid dialog stacking confusion on macos.
Also, the cloud projects dialog was mishandling its visible state (calling self.hide() prior to opening the login window only to have it re-shown after constructor (by show_cloud_overview_dialog(self)). This lead to the (disabled) projects dialog being focused instead of the login dialog. I suspect that will also alleviate whatever is going on with macos.
=> Insure login dialog is front and center

.docker/Dockerfile, .github/workflows/continuous_integration.yml, .gitignore, .gitmodules, qfieldsync/__init__.py, qfieldsync/core/cloud_converter.py, qfieldsync/core/cloud_project.py, qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/checker_feedback_table.py, qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/gui/layers_config_widget.py, qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/package_dialog.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/gui/synchronize_dialog.py, qfieldsync/tests/test_export.py, qfieldsync/utils/cloud_utils.py, qfieldsync/utils/qgis_utils.py, requirements.txt
Depends on
- https://github.com/opengisch/qgis-plugin-ci/pull/230
- https://github.com/opengisch/libqfieldsync/pull/49
Developer information, to work locally, either install the `requirements.txt` (if you don't need to edit libqfieldsync) or pip install libqfieldsync as editable if you need to work on libqfieldsync.
```sh
git clone git@github.com:opengisch/libqfieldsync.git
pip install -e libqfieldsync
```
=> Package libqfieldsync as wheel

qfieldsync/gui/map_layer_config_widget.py, qfieldsync/ui/map_layer_config_widget.ui
This PR implements a functionality in qfieldsync allowing users to determine the locked geometry state of individual features within a vector layer.
First, here's a screenshot of the UI:
A brand new data-defined property button sits next to the [x] lock geometry checkbox. From there, users can select a feature attribute or build a more complex expression that will change the locked geometry status of individual features.
_(Requires https://github.com/opengisch/libqfieldsync/pull/58 on the libqfieldsync side of things)_
=> Implement a feature-based geometry lock mechanism

.github/workflows/continuous_integration.yml, .github/workflows/documentation.yml, qfieldsync/core/preferences.py, qfieldsync/gui/preferences_widget.py, qfieldsync/qfield_sync.py, qfieldsync/ui/preferences_widget.ui
This will need a bit of documentation tweaked. In an attempt to streamline the QField experience for newcomers, we are now hiding cable export/import toolbar buttons so the cloud path becomes "clearer". The cable actions are still available in the plugins -> QFieldSync sub menu, and _can be made visible in the toolbar_ view a new setting checkbox.
UI:
Looks:
=> New setting to toggle visibility of non-cloud packaging toolbar buttons, hide by default

qfieldsync/qfield_sync.py
Fixing an issue that's been bugging me every time I right clicked on the QGIS main window toolbar area:
Every single item ends with Toolbar except QFieldSync, let's fix that. The PR also makes the label translatable. Win-win.
=> Properly name the QFieldSync toolbar

requirements.txt
Fix https://github.com/opengisch/qfieldsync/issues/552
=> Make QFieldSync work with older QGIS versions prior to 3.30

qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui, requirements.txt
This PR implements a mechanism through which users/managers of cloud projects can force enable auto-push on QField devices in the field as well as dictating the interval in minutes:
=> Allow users to force auto-push and manage time interval via project configuration

qfieldsync/gui/package_dialog.py, requirements.txt
Fixes https://github.com/opengisch/qfieldsync/issues/564 
(https://github.com/opengisch/libqfieldsync/pull/72 needed)
=> Fix packaging for cable does not respect area of interest settings

qfieldsync/gui/package_dialog.py, requirements.txt
A regression slipped into 4.8.0 with regards to basemap creation during cable export.
Long story short, the UI is a bit deceptive and makes it look like the area of interest is only tied to filtering of feature when in fact it's also tied to basemap creation.
Requires https://github.com/opengisch/libqfieldsync/pull/73
=> Fix creation of basemap when feature filtering isn't enabled

qfieldsync/gui/map_layer_config_widget.py, qfieldsync/ui/map_layer_config_widget.ui, requirements.txt
In the future, it'd be great to have the UX implemented in QGIS itself. But for now, let's rely on our beloved qfieldsync to implement a simple layer-level configuration:
=> Implement UI to control the new value map editor widget's toggle buttons interface

qfieldsync/ui/cloud_login_dialog.ui
Before:
PR:
And just like that, the register an account hyperlink is becoming readable! :)
=> Do not hardcode a hyperlink color, let the system handle it

qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui, requirements.txt
This PR adds a couple of widgets to setup geofencing in QField. Looks:
The libqfieldsync counterpart is here: https://github.com/opengisch/libqfieldsync/pull/86
=> Implement geofencing settings in the project properties' QField panel

qfieldsync/gui/mapthemes_config_widget.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui, requirements.txt
This PR implements the project configuration UI to setup the default active layer QField will pick when users select a map theme in QField. The functionality allows for project managers to help out field workers by auto-picking the right active layer to digitize entries based on map themes.
Screenshot:
=> Add map themes's default active layer configuration

qfieldsync/gui/mapthemes_config_widget.py
This PR fixes issue #611 .
@m-kuhn , as discussed earlier.
=> Fix broken compatibility with QGIS 3.18

requirements.txt
Based on: https://github.com/opengisch/libqfieldsync/pull/95
=> Adding validator for files on converter to cloud project

qfieldsync/gui/package_dialog.py, qfieldsync/tests/test_export.py, qfieldsync/ui/package_dialog.ui, requirements.txt
This adds the option to specify a new project name and title in the exported project when packaging.
| Before | After |
|--------|-------|
| ![Before Image](https://github.com/user-attachments/assets/543f0fc9-4034-463e-a638-1a0b453281fc) | ![After Image](https://github.com/user-attachments/assets/9ad7c145-a6b8-454a-98a3-496c6ae21ef9) |
Related PR: https://github.com/opengisch/libqfieldsync/pull/94
=> Adding the option for specify the project title on packaged project

qfieldsync/core/cloud_api.py
Here I propose to ignore paths that start with "/api" or that are equal to "/" to remove unnecessary parts, but to keep other ones to avoid 404 errors.
=> correction poposition for issue 605

README.md
Got some inspiration from QField's Contributing text.
Also added a section that is clear about libqfieldsync.
=> Added Contributing section and improved Development section in the README

requirements.txt
The PR involves the changes from:
https://github.com/opengisch/libqfieldsync/pull/96 
https://github.com/opengisch/libqfieldsync/pull/97
=> Update requirements.txt to use the latest libqfieldsync

qfieldsync/core/preferences.py
Probably not the best way to solve it, but the easiest with no serious consequences.
If the user install QFieldSync and the default value of `qfieldCloudRememberMe=True`, it will call the `cloud_api.auto_login_attempt`, which calls the `QgsApplication.authManager()`.
As a UI this is asking for the master password, but the users have no idea what is this and what is the context of it. 
Fix https://github.com/opengisch/qfieldsync/issues/580
=> Do not show `master password` when using QFieldSync for the first time

qfieldsync/gui/package_dialog.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui, requirements.txt
This PR adds the basemap tiles min and max zoom levels, in a project's QField settings form, for generating `mbtiles` during cable export.
2 new `QgsSpinBox` widget now appear at the bottom of the `Base Map` form:
See [this `libqfieldsync` PR](https://github.com/opengisch/libqfieldsync/pull/105) for more details and steps.
=> Add basemap tiles min and max zoom to project's qfield settings form

qfieldsync/ui/cloud_login_dialog.ui
Following the suggestion in this PR
https://github.com/opengisch/qfieldsync/pull/641
=> Add tooltip to the QFieldCloudIcon

qfieldsync/ui/cloud_create_project_widget.ui
Added a sentence of clarification, trying to improve the confusion raised in https://github.com/opengisch/QField-docs/issues/546
=> Add clarification that the second option in QFieldSync should be used for PostGIS connections

qfieldsync/gui/project_configuration_widget.py
The attachment directories list widget's height can get really small - ie _too_ small - when expanding a couple of group boxes in there. 
While the whole project configuration panel deserves a re-styling, this PR provides a nice band-aid by adding a minimum height so the list remains usable.
=> Fix attachment directories list widget's tiny height issue

qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui
More polishing and improvements to the cloud project transfer dialog, this time on the panel that has users pick which files are uploaded/download to/from the cloud:
- on dark themes, the local project directory text edit widget was looking bad, the PR fixes that by avoiding hardcoded stylesheet colors
- the project hyperlink that's meant to bring users to the project page on the web did not work, fixed
- the local project directory didn't offer much at all in terms of UI/UX, a button has been added so users can open it directly
Beyond that, I've re-ordered the widgets a bit so the panel focuses on the job at hand, i.e. to transfer files. The project's hyperlink to the web app (the project name being already int the dialog title bar) and the local directory text edit widgets are secondary …
=> Cloud project transfer dialog bug hunting and improvements, part 2

.github/workflows/continuous_integration.yml, qfieldsync/__init__.py
When we add a new class/method/API change in `libqfieldsync` and we use it within QFieldSync plugin, we get a runtime error, such as:
```
ImportError: cannot import name 'PackagingCanceledException' from 'libqfieldsync.offline_converter' (C:\Users\paul.bennett\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offline_converter.py)
```
The reason is that `libqfieldsync` is loaded from a `.whl` file, which is cached by the Python runtime and we need to introduce this magic to force reload this.
The magic consists of two parts:
1) ensure the new version .whl file has a different name 2) ensure we use `importlib.reload` to force reload from the new .whl
Tested on Windows 11 with QGIIS 3.34. Failed to reproduce on Ubuntu, but also did not try …
=> Fix runtime error after plugin update when `libqfieldsync` changed API

qfieldsync/core/cloud_api.py, qfieldsync/core/cloud_project.py, qfieldsync/core/cloud_transferrer.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui
This PR takes on the work done by @tdrivas and finishes the handling of localized datasets upload when synchronizing a cloud project.
The following additions are in the PR:
- we do not rely on QgsProject.instance() to get localized datasets but instead we do it by temporarily opening a locally stored cloud project file to fetch them
- the upload relies on the ThrottledFileTransfer class, which gives us UI feedback and control over how many files we upload at the same time
- we rely on project cache to avoid hard-coded project fetch
- a minimal UI was added to allow for users to skip localized dataset upload (see the screenshot below):
I've been re-thinking about this, and IMHO, we should actually avoid uploading a localized dataset when it's present remotely but has a different checksums. …
=> Seamless localized datasets upload support

qfieldsync/core/cloud_transferrer.py
Spotted while doing some testing in preparation for QField 3.6.
=> Fix error when attempting to launch a transfer without providing a localized_dataset project

qfieldsync/core/preferences.py
We should have done this a long time ago -- once upon a time, when we added audio, video, and other file attachments support, the default expression has files put in more than a single DCIM directory. If the users to not add these extra folders, they will end up not able to package attachments when downloading the project on QField devices (i.e. https://github.com/opengisch/QField/issues/6409)
=> Add additional default attachment directories to cover all default attachment expressions

qfieldsync/gui/map_layer_config_widget.py, qfieldsync/ui/map_layer_config_widget.ui, requirements.txt
Until now, our [x] lock geometry toggle was locking quite a lot. It was locking:
- feature addition
- feature deletion
- geometry modification
Users have requested a finer grained set of locks. This PR implements that by adding 4 distinct locked states:
- feature addition
- feature deletion
- geometry modification
- attribute editing (a nice 4th lock here that was not possible before)
Each of these locks come with a data-defined property that allows for the locks to be turned on/off based on expressions evaluated against a given feature and/or various scopes.
Here's how it looks UI-wise:
Note that on the UI side, we're letting go of the word "lock" in favor of a wording that aims at being easier to understand.
=> Explode geometry locked into 4 distinct locked states

qfieldsync/core/preferences.py, qfieldsync/gui/directories_configuration_widget.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/directories_configuration_widget.ui, qfieldsync/ui/project_configuration_widget.ui
This PR revamps the attachment directories UI found in the project properties dialog, and adds a new "data" directory type. Here's how it looks:
- A clear way to add new directories (i.e., users don't need to guess that double clicking on a blank row is the way you add a row :))
- A clear way to remove directories
The need for a new data directory type emerged since we added on-demand attachment download in QField/QFieldCloud. If attachments are downloaded on demand, our project plugin / symbology / decoration assets placed in a subfolder still needs to be downloaded. That will now happen with data directories.
=> Project properties' attachment directories UI revamp

qfieldsync/core/cloud_transferrer.py, qfieldsync/utils/file_utils.py
Apparently the passed `mode` value on `os.mkdir` and `Path.mkdir` is not respected by Windows prior to 3.13. What is more, in 3.13 Windows will handle only 0o700, the rest of the values will be ignored.
=> fix: on windows the newly created fs directories might not be deletable

qfieldsync/gui/map_layer_config_widget.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/map_layer_config_widget.ui, qfieldsync/ui/project_configuration_widget.ui
_Preface: the motivation for this PR comes as I'm about to introduce another attachment-related project configuration into QFieldSync and I did *not* want to simply throw another setting in the advanced settings groupbox, which had become an aggregation of everything under the sun._
This PR focuses on restructuring the QFS project properties widget, as well as add short introduction labels to sections to provide preliminary guidance to users. This adopts a practice increasingly used in QGIS itself and IMHO can be quite useful in better sharing the purpose of various settings.
Before (left) vs. PR (right):
Improvements here include:
- the regrouping of AOI and base map together; these settings work together and it was really not that clear before now
- an explicit, visual guide as to what …
=> Project properties restructuring and UX improvements

qfieldsync/gui/image_stamping_configuration_widget.py, qfieldsync/gui/project_configuration_dialog.py, qfieldsync/gui/project_configuration_widget.py, qfieldsync/qfield_sync.py, qfieldsync/ui/image_stamping_configuration_widget.ui, qfieldsync/ui/project_configuration_widget.ui, requirements.txt
This PR adds image stamping customization functionality, available in the project properties' QField panel. First, screenshot time:
As the screenshot shows above, the stamping customization widgets are offered in a sub-panel which can be opened by click on its settings button within the attachments tab here:
I'm quite happy about the introduction of a panels stack here, it should give us plenty of space to grow in the future.
The image stamping customization allows for users to:
- customize the details being stamped via the crafting of an expression-based multiline string
- customize the font color/size/drop shadow/etc. used to render the details
- customize the position (left / center / right) of the details
- add an image decoration overlay on top of the image being stamped
- force …
=> Add image stamping customization functionality

qfieldsync/gui/cloud_transfer_dialog.py
This pull request guards users from unknowingly overwrite datasets tied to layers set to offline editing when triggering a cloud transfer push/pull within QFieldSync. 
Instead of automatically setting the upload/download action for datasets tied to layers being offlined to _upload_ when the dataset's local modified time is more recent than what is on QFieldCloud, the cloud transfer dialog now defaults to _no action_. That is meant to prevent accidental upload and force the users to be intentional about the action for such datasets.
For non-datasets or datasets set to direct access, nothing changes. Similarly, if a dataset that is set to offline editing has a modification time that is more recent than the locally stored file, we are still auto-setting the action to download, nothing …
=> Add logic to avoid auto uploading offline editing-driven datasets to QFieldCloud

qfieldsync/core/cloud_converter.py, qfieldsync/gui/cloud_create_project_widget.py, qfieldsync/gui/cloud_transfer_dialog.py, qfieldsync/gui/package_dialog.py, qfieldsync/ui/cloud_transfer_dialog.ui, requirements.txt
See https://github.com/opengisch/libqfieldsync/pull/120
Also took the opportunity to remove some code branching for pluralization that is actually taken care of by Transifex+translators+qt translation framework.
See the table in the plurals section: https://doc.qt.io/archives/qt-5.15/i18n-source-translation.html#handling-plurals
=> refactor: rename all "localized datasets" to "shared datasets"

qfieldsync/gui/map_layer_config_widget.py
=> Fix crash when opening a non-vector map layer properties dialog

qfieldsync/gui/project_configuration_widget.py, qfieldsync/ui/project_configuration_widget.ui
This PR intends to make the basemap generation parameters less confusing.
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/dce435a8-37d4-4674-a3f1-d3a1436ad85c) | ![image](https://github.com/user-attachments/assets/a1d1a1b4-48bd-43f4-a4dc-4b4fd1ceb8d9) |
3 possible values for the basemap tile size parameter, which is now picked within a ComboBox : 256, 512 and 1024.
See the sister-PR on libqfieldsync: https://github.com/opengisch/libqfieldsync/pull/117
=> ui(basemap): clean up basemap generation parameters

qfieldsync/gui/cloud_browser_tree.py, qfieldsync/gui/cloud_transfer_dialog.py
Passing lambdas in qt signal handlers makes code easier to write (and perhaps read), but adds an unexpected reference to object that is not deleted (the lambda function) and keeps the whole reference of a Qt Object that should have been deleted already.
Steps to reproduce:
1) open QFieldSync
2) disable/enable the plugin multiple times very fast (or use Plugin Reloader)
3) you should be presented with an error like:
```
RuntimeError: wrapped C/C++ object of type QFieldCloudRootItem has been deleted
Traceback (most recent call last):
File "/home/suricactus/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/cloud_browser_tree.py", line 79, in
self.network_manager.token_changed.connect(lambda: self.update_icon())
^^^^^^^^^^^^^^^^^^
File …
```
=> fix: do not pass lambdas on deletable objects from qt

requirements.txt
See https://github.com/opengisch/libqfieldsync/pull/121
=> fix: do not allow "Directly access datasource" on QFieldCloud packaging actions for file based layers that are not readonly

qfieldsync/gui/cloud_transfer_dialog.py
My bad, we should be carefult for these splits in reviews. The latest QFS is broken on devices with older Python.
=> fix(typing): older python versions do not support ` | None` type def yet

qfieldsync/ui/project_configuration_widget.ui
Fix regression from rebase commit here (https://github.com/opengisch/qfieldsync/commit/45333da5a514336bfb9354306d79d6413bc9a54e) whereas the checkbox that dictate whether layers being offlined should only copy features interesting the AOI was renamed to "map theme", and added to the "buttonGroup" group, which led to a broken checkbox state.
@gounux , gentle ping.
=> Fix offlining feature intersecting AOI checkbox
